/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.kotlin

import org.dotenv.vault.dotenvVault

class App {
    val dotenv = dotenvVault()
    val hello = dotenv["HELLO"]
    val greeting: String
        get() {
            return "Hello $hello!"
        }
}

fun main() {
    println(App().greeting)
}
