/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.kotlin

import io.github.cdimascio.dotenv.dotenv

class App {
    val dotenv = dotenv()
    val hello = dotenv["HELLO"]
    val greeting: String
        get() {
            return "Hello $hello!"
        }
}

fun main() {
    println(App().greeting)
}
